### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by jehanjen** [seblful/label-studio-yolov8-backend#3]
hello...
i followed the steps but i have error (Validation error) and i checked the terminal i got this error ( FileNotFoundError: [Errno 2] No such file or directory: 'best.pt') but i have best.pt in the main folder but the same error.

**Comment by seblful** [comment]
try to change model path to absolute path

**Comment by jehanjen** [comment]
> try to change model path to absolute path

I change best.pt to the path of best.pt but with the same issue

**Comment by seblful** [comment]
Do you have YOLOv8 model best.pt in your directory??

**Comment by jehanjen** [comment]
> have

Yes i have..
Fist step i clone the repository 
Then i past token ip to  model .py
Third i add best.pt to the folder
Then docker compose up
And i got the error.

**Comment by jehanjen** [comment]
> Do you have YOLOv8 model best.pt in your directory??

So you have any idea about the error?

**Comment by seblful** [comment]
Idk actually, you could create container without best.py in it, check it out

After any changes you must recreate container or use docker volumes instead of it

**Comment by jehanjen** [comment]
> Idk actually, you could create container without best.py in it, check it out
> 
> After any changes you must recreate container or use docker volumes instead of it

Ok..i will check it then i will let you know.
Thank you so much.

**Comment by jehanjen** [comment]
> > Idk actually, you could create container without best.py in it, check it out
> > After any changes you must recreate container or use docker volumes instead of it
> 
> Ok..i will check it then i will let you know. Thank you so much.

![1](https://github.com/seblful/label-studio-yolov8-backend/assets/141221046/2ba88743-421b-442f-8903-b9175c0bc5c3)

**Comment by jehanjen** [comment]
> > Idk actually, you could create container without best.py in it, check it out
> > After any changes you must recreate container or use docker volumes instead of it
> 
> Ok..i will check it then i will let you know. Thank you so much.

![2](https://github.com/seblful/label-studio-yolov8-backend/assets/141221046/99961dc8-1108-474f-9a0c-0104b28903a3)

**Comment by jehanjen** [comment]
> > > Idk actually, you could create container without best.py in it, check it out
> > > After any changes you must recreate container or use docker volumes instead of it
> > 
> > 
> > Ok..i will check it then i will let you know. Thank you so much.
> 
> ![1](https://private-user-images.githubusercontent.com/141221046/306561801-2ba88743-421b-442f-8903-b9175c0bc5c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDY1OTcsIm5iZiI6MTcwODUwNjI5NywicGF0aCI6Ii8xNDEyMjEwNDYvMzA2NTYxODAxLTJiYTg4NzQzLTQyMWItNDQyZi04OTAzLWI5MTc1YzBiYzVjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwOTA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmMyNTE3ZWM2ZDI0OGI0YzQ0NDBmODNjOWRkZDBlZDc0NWI3NzY0NTI4YzIzMWZkZDRlNGU0YTc0NmJmYWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dLTpY3PKrtqV6i_PBXRqGiiFx9PY18WGR0tt1ftbEuI)

the same error ..

**Comment by jehanjen** [comment]
> Idk actually, you could create container without best.py in it, check it out
> 
> After any changes you must recreate container or use docker volumes instead of it

![2](https://github.com/seblful/label-studio-yolov8-backend/assets/141221046/3b5a7286-b3d2-4fbf-ba4d-e325bc936511)

**Comment by seblful** [comment]
Have you deleted all old docker images and created a new one before creating container?

**Comment by jehanjen** [comment]
> Have you deleted all old docker images and created a new one before creating container?

yes

**Comment by jehanjen** [comment]
now its connected to the docker but with out of result, there is no auto_annotate?

**Comment by seblful** [comment]
you should read label-studio [documentation](https://labelstud.io/guide/ml.html) to find the answer
